# commands a player can use to get a response message. This can be used to request links like socials, dynmap, store etc. 
commands:
  discord:
    # The command and its aliases.
    command:
      - discord
      - dc
    
    # For colored text the & symbol is used. The symbol is escapeable with a slash (/&).
    response: "&1Join our Discord server: https://discord.gg/example"
    # Optional: The message sent to Bedrock players (if different from the normal response). This only works in combination with the geyser floodgate plugin.
    # This is a function because Bedrock players can't click on links, so you might want to give them different instructions.
    bedrock_response: "&1Join our Discord server: https://discord.gg/example"
    click: "https://discord.gg/example"
    hover: "Click to open the Discord invite link"


  map:
    # If there is only one command, you don't have to specify it. If not specified, the key will be used as command.
    # command:
    # - map
    response: "Check out the map here: https://map.example.com"
    bedrock_response: "Check out the map here: https://map.example.com"
    click: "https://map.example.com"

messager:
  # send a message every X minutes
  interval: 300
  # if true, a random message will be chosen from the list. If false, messages will be sent in order.
  random: true

  messages:
    - "&9Join our discord for the rules and to stay updated, &7/discord"
    - "&6View the worldmap via &8/map"
    - "&6Don't forget to &c/vote &6for cool rewards, every vote helps the community grow!"
  # Optional: Different messages for Bedrock players (if different from the normal messages). This only works in combination with the geyser floodgate plugin.
  # With the geyser plugin, bedrock players will only get messages from this list, unless it's empty or missing.
  bedrock_messages:
    - "&9Join our discord for the rules and to stay updated: &7https://discord.gg/23m7a5eVZy"
    - "&6View the worldmap at: &8https://map.spoxy.net"