# commands a player can use to get a response message. This can be used to request links like socials, dynmap, store etc. 
commands:
  discord:
    # The command and its aliases.
    command:
      - discord
      - dc
    
    # For colored text the & symbol is used. The symbol is escapeable with a slash (/&).
    response: "&1Join our Discord server: https://discord.gg/example"
    # Optional: The message sent to Bedrock players (if different from the normal response). This only works in combination with the geyser floodgate plugin.
    # This is a function because Bedrock players can't click on links, so you might want to give them different instructions.
    bedrock_response: "&1Join our Discord server: https://discord.gg/example"
    click: "https://discord.gg/example"
    hover: "Click to open the Discord invite link"


  map:
    # If there is only one command, you don't have to specify it. If not specified, the key will be used as command.
    # command:
    # - map
    response: "Check out the map here: https://map.example.com"
    bedrock_response: "Check out the map here: https://map.example.com"
    click: "https://map.example.com"