main: net.spoxy.SimpleServerMessage
name: SimpleServerMessage
version: 1.1.0

softdepend:
  - floodgate

commands:
  ssmReload:
    description: Reload the SimpleServerMessage config
    usage: /ssmreload
    permission: SimpleServerMessage.ssmReload
    permission-message: You do not have permission to use this command.

permissions:
  SimpleServerMessage.ssmReload:
    description: Allows reloading the SimpleServerMessage config
    default: op